# Generated by Django 5.2.8 on 2025-12-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="default.png", upload_to="profile_images/"),
        ),
    ]
