# Generated by Django 5.2.8 on 2025-12-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
